sudo: required

langauge: go

services:
    - docker

script:
    - docker build -f Dockerfile
      --build-arg VCS_REF=`git rev-parse --short HEAD`
      --build-arg BUILD_DATE=`date -u +"%Y-%m-%dT%H:%M:%SZ"`
      -t mcfio-openvpn-client .

after_success:
    - docker login -u $DOCKER_USER -p $DOCKER_PASS
    - docker tag mcfio-openvpn-client mcfio/openvpn-client:latest
    - docker push mcfio/openvpn-client:latest
